package OOPS;

public class Constructors {
    public static void main(String args[]){
        Child s1= new Child();
        s1.name="Vaish";
        s1.roll=234;
        s1.password="abc";
        s1.marks[0]=88;
        s1.marks[1]=95;
        s1.marks[2]=90;

        //s1 forgot his password
        Child s4 = new Child(s1);
        s4.password="asddf";

        //this change in s1 will also result in s4
        s1.marks[0]=100;
        s1.name="Shantanu"; //this wont change the value of s4 cause it is not an array

        for(int i=0;i<3;i++){
            System.out.println(s4.marks[i]);
        }
        System.out.println(s4.name);


        Child s2= new Child("Vaishali");
        Child s3= new Child(10);
        //Error- no constructor defined with two properties Child s4 = new Child("Vaishali", 123);
    }
}

class Child{
    String name;
    int roll;
    String password;
    int marks[];
    //SHALLOW COPY CONSTRUCTOR
    // Child(Child s1){
    //     marks=new int[3];
    //     this.name=s1.name;
    //     this.roll= s1.roll;
    //     this.marks=s1.marks; //array-> reference copy 
    //     //properties of s1 is copied to s2
    // }

    //DEEP COPY CONSTRUCTOR
    Child(Child s1){
        marks= new int[3];
        this.name=s1.name;
        this.roll=s1.roll;

        for(int i=0;i<3;i++){
            this.marks[i]=s1.marks[i];
        }
    }


    //NON PARAMETERIZED CONSTRUCTOR
    //If we comment out this constructor then Child s1= new Child(); will give us an error as this should be defined if you are 
    //defining other constructors as well- if no Constructor defined it will automatically get generated by java
    Child(){
        marks=new int[3];
        System.out.println("Constructor is called...");
    }

    //PARAMETERIZED CONSTRUCTOR
    Child(String name){
        marks=new int[3];
        this.name=name;
    }

    //MULTIPLE CONSTRUCTORS CAN BE THERE- They are matched accordingly --> CONSTRUCTOR OVERLOADING 
    Child(int roll){
        marks=new int[3];
        this.roll=roll;
    }
}